apiVersion: awsblueprints.io/v1alpha1
kind: DynamoIRSA
metadata:
  name: dynamo-irsa-test
spec:
  writeConnectionSecretToRef:
    name: dynamo-irsa-test
  resourceConfig:
    region: us-east-2
    tags:
      namespace: team-x
      cluster: crossplane-v5
  dynamoConfig:
    billingMode: PAY_PER_REQUEST
    attribute:
      - name: ID
        type: S
    hashKey: ID
